# Generated by Django 6.0.4 on 2026-04-12 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('claimed', 'Claimed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_matches', to='items.founditem')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_matches', to='items.lostitem')),
            ],
            options={
                'ordering': ['-match_score', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('lost_item', 'found_item'), name='matches_itemmatch_unique_lost_found')],
            },
        ),
    ]
